---
title: "data_cleaning_2019"
author: "AnMei Chen"
date: "11/28/2021"
output: github_document
---

```{r}
library(tidyverse)
library(readxl)
```

## 2019 export by values and volumes

```{r}
exports_volume_df = 
  read_excel("data/2019 Exports.xlsx",sheet = "Volumes", range = "A3:M22") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    january:december,
    names_to = "Month",
    values_to = "Export_Volume"
  ) %>% 
  rename("Item" = "items")

exports_values_df = 
  read_excel("data/2019 Exports.xlsx",sheet = "Values", range = "A10:M36") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    january:december,
    names_to = "Month",
    values_to = "Export_Value"
  ) %>% 
  rename("Item" = "items")

write.csv(exports_volume_df, file = ".\\data\\Export Volume Clean 2019.csv", row.names = F)

write.csv(exports_values_df, file = ".\\data\\Export Value Clean 2019.csv", row.names = F)

```

## 2019 imports by values and volumes

```{r}
imports_volume_df =
  read_excel("data/2019 imports.xlsx",sheet = "Volumes", range = "A3:M16") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    january:december,
    names_to = "Month",
    values_to = "Import_Volume"
  ) %>% 
  mutate(
    items = recode(items, "Wine 4/" = "Wine", "Malt beverages 4/" = "Malt beverages")
  ) %>% 
  rename("Item" = "items")

imports_values_df =
  read_excel("data/2019 imports.xlsx",sheet = "Values", range = "A10:M38") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    january:december,
    names_to = "Month",
    values_to = "Import_Value"
  ) %>% 
  rename("Item" = "items")


write.csv(imports_volume_df, file = ".\\data\\Import Volume Clean 2019.csv", row.names = F)

write.csv(imports_values_df, file = ".\\data\\Import Value Clean 2019.csv", row.names = F)
```

## 2019 Top 10 U.S. export markets for soybeans, corn, wheat, and cotton, by volume	

```{r}
soybeans_df =
  read_excel("data/2019 Top 10 exports.xlsx",sheet = "2019", range = "A7:M17") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    january:december,
    names_to = "Month",
    values_to = "Export_Volume"
  ) %>% 
  add_column("Commodity" = "soybean")

corn_df =
  read_excel("data/2019 Top 10 exports.xlsx",sheet = "2019", range = "A20:M30") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    january:december,
    names_to = "Month",
    values_to = "Export_Volume"
  ) %>% 
  add_column("Commodity" = "corn")

wheat_df =
  read_excel("data/2019 Top 10 exports.xlsx",sheet = "2019", range = "A33:M43") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    january:december,
    names_to = "Month",
    values_to = "Export_Volume"
  ) %>% 
  add_column("Commodity" = "Wheat,unmilled")

wheat_df =
  read_excel("data/2019 Top 10 exports.xlsx",sheet = "2019", range = "A46:M56") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    january:december,
    names_to = "Month",
    values_to = "Export_Volume"
  ) %>% 
  add_column("Commodity" = "Cotton,ex linters")

top_10_exports_df = 
  rbind(soybeans_df,corn_df,wheat_df,wheat_df) %>% 
  relocate(Commodity,.before = Month) %>% 
  rename("Export_Country" = "country") %>% 
  mutate(
    Export_Country = recode(Export_Country, "European Union-28 3/" = "European Union-28")
  )
  
write.csv(top_10_exports_df, file = ".\\data\\Top 10 Export Clean 2019.csv", row.names = F)

```


##2019 Top 10 sources of U.S. imports of fruits and vegetables, by value

```{r}
fresh_fruits_df =
  read_excel("data/2019 Top 10 imports.xlsx",sheet = "2019", range = "A8:M18") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    january:december,
    names_to = "Month",
    values_to = "Import_Value"
  ) %>% 
  add_column("Commodity" = "Fruits, fresh or frozensoybean")

prepared_fruits_df =
  read_excel("data/2019 Top 10 imports.xlsx",sheet = "2019", range = "A21:M31") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    january:december,
    names_to = "Month",
    values_to = "Import_Value"
  ) %>% 
  add_column("Commodity" = "Fruits, prepared or preserved")

fresh_vege_df =
  read_excel("data/2019 Top 10 imports.xlsx",sheet = "2019", range = "A34:M44") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    january:december,
    names_to = "Month",
    values_to = "Import_Value"
  ) %>% 
  add_column("Commodity" = "Vegetables, fresh or frozen")

prepared_vege_df =
  read_excel("data/2019 Top 10 imports.xlsx",sheet = "2019", range = "A47:M57") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    january:december,
    names_to = "Month",
    values_to = "Import_Value"
  ) %>% 
  add_column("Commodity" = "Vegetables, prepared or preserved")

top_10_imports_df = 
  rbind(fresh_fruits_df,prepared_fruits_df,fresh_vege_df,prepared_vege_df) %>% 
  relocate(Commodity,.before = Month) %>% 
  rename("Import_Country" = "import_country") %>%
  mutate(
    Import_Country = recode(Import_Country, "European Union-28 3/" = "European Union-28")
  ) 

write.csv(top_10_imports_df, file = ".\\data\\Top 10 Import Clean 2019.csv", row.names = F)
```

