---
title: "Correlation between US Foreign Agricultural Trade and COVID-19 Impact"
output: github_document
---
# Group Members(name and uni):
Xuanhe Chen (xc2610)

Xinyi Zhou (xz3078)

Lynn Chen (lc3605)

AnMei Chen (ac4964)

Zoey Zhao (zz2899)

# Motivation: 

The message Americans have been getting about inflation in recent months can be expressed in one word: frightening. Last year, as COVID-19 affected the world economy and disrupted trade flows, which also has had unprecedented effects on all dimensions of human life. Yet, it is certainly not our imagination: groceries do cost more now than prior to pandemic. The increase in food prices that we’ve seen over the past eight months is real and meaningful. According to the U.S. Bureau of Labor Statistics, food prices overall rose about 4.6% since September 2020. 
The effects of pandemic have been felt in almost every sector, and the agricultural market is no different. Our project intends to look deeper into the impact of Covid-19 on agricultural trade and how it's affecting both supply and demand.

# Intended Final Products:
We would like to use data visualization with graphs to analyze the effect of Covid-19 pandemic on U.S. agricultural imports and exports including finding the top 3 agricultural products that have been affected most by Covid-19 in import and export. We are also interested in finding the impact of Covid-19 on top 10 export countries for wheat, corn, soybeans, and cotton from the U.S. 

# The Anticipated Data Sources:
We would use the Foreign Agricultural Trade of the United States (FATUS) data of 2018 to 2021 from the USDA public government research service: 
https://www.ers.usda.gov/data-products/foreign-agricultural-trade-of-the-united-states-fatus/u-s-agricultural-trade-data-update/ 

And Public COVID-19 daily report from COVID-19 Data Repository by the Center for Systems Science and Engineering (CSSE) at Johns Hopkins University:
https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports_us 

# Planned Analysis and Visualizations
We will first clean the data of U.S. agricultural trade value by month for 2018-2020, and calculate the average monthly import values before (2018-2019) and after (2020-2021) Covid-19 as well as average monthly export values before and after Covid-19. An ideal visualization will be a two-panel (export value/import value) spaghetti plot with month of a year as x-axis, average export/import value as y-axis, and colored by before/after Covid-19. 

Then, we will clean the data of U.S. agricultural import/export value by product type in each year from 2018 to 2021 and calculate the average export/import value of each product type for 2018-2019 and 2020-2021. A two-panel (export value/import value) bar chart will be generated with product type as x-axis, average export/import value as y-axis, and colored by before/after Covid-19. Alternatively, we could do the same analysis and visualization on data of U.S. agricultural import/export volume by product type. 

For the third plot, we would use the data of top 10 U.S. export markets for soybeans, corn, wheat, and cotton (by volume) in each year from 2018 to 2021. Same as the previous two plots, we will calculate the average export volume of each country for 2018-2019 and 2020-2021. A bar chart will be generated with country as x-axis, export volume as y-axis, and colored by before/after Covid-19. However, the data for top 10 import sources only has import value, so doing the same analysis and visualization on this data set, we will generate another plot with y-axis of import value. 

The last plot will be a two-panel scatter plot revealing the correlation between the number of Covid-19 cases in the U.S. and the volume of import/exports with a regression line generated by linear regression. The number of Covid-19 cases by month will be the x-axis and monthly volume of monthly imports/exports will be the y-axis.


# The Planned Timeline:


|  Objective    |   Schedule    |
| ------------- | ------------- |
| Submit a Proposal   | November 13 |
| Additional research  | November 14-16 |
| Proposal review meeting   | November 16 - 19 |
| Data scraping and data cleaning  | November 20 -23 |
| Exploratory analyses, statistical analyses and visualizations | November 24 - December 1 |
| Summarize key findings and results | December 2 - December 3 |
| Additional analysis |December 4 - December 5|
| Written report |December 6 - December 8|
| Webpage and screencast |December 9 - December 10|
| Submit final project |December 11 |
